# tools/export_kernels.jl
#
# Writes the exact column polynomials of every kernel (values and derivatives), and the
# ghost-point matrices of the boundary conditions, as Rust source for convinterp. Every
# coefficient comes from ConvolutionInterpolations.jl, so both implementations use identical values.
#
# Usage, from the convinterp folder:
#     julia --project=C:\Users\Nikolaj\Git\ConvolutionInterpolations.jl tools/export_kernels.jl src/kernels.rs
# Writes only the file given as the argument.

using ConvolutionInterpolations
const CI = ConvolutionInterpolations

# Kernels with polynomial columns (:a0 is piecewise constant, handled separately in Rust), with the
# highest derivative order the Julia package defines for each
const MAX_DERIVATIVE = Dict(:a1 => 0, :a3 => 1, :a4 => 1, :a5 => 1, :a7 => 1,
                            :b5 => 3, :b7 => 5, :b9 => 6, :b11 => 7, :b13 => 7)
const KERNELS = (:a1, :a3, :a4, :a5, :a7, :b5, :b7, :b9, :b11, :b13)
# Kernels with ghost points (:a0 and :a1 have none) and their polynomial ghost matrices
const GHOST_KERNELS = (:a3, :a4, :a5, :a7, :b5, :b7, :b9, :b11, :b13)

# Rust constant name, e.g. B5_D2 for kernel :b5, derivative order 2
const_name(kernel, order) = uppercase(string(kernel)) * "_D$order"

# The columns of a kernel and order as rows of Float64 coefficients, from the highest power of
# τ down (the order Horner's scheme uses), one entry per column; and the number of columns
function table_rows(kernel, order)
    columns = CI._column_polynomials_exact(kernel, order)   # column c: coefficients of τ^0, τ^1, …
    degree = maximum(length, columns) - 1
    rows = [[k <= length(col) ? Float64(col[k]) : 0.0 for col in columns] for k in degree+1:-1:1]
    return rows, length(columns)
end

# Write a ghost matrix as a Rust GhostMatrix constant, row by row (row j: ghost point j)
function write_ghost_matrix(io, name, matrix)
    println(io)
    println(io, "pub const $name: GhostMatrix = GhostMatrix {")
    println(io, "    rows: $(size(matrix, 1)),")
    println(io, "    cols: $(size(matrix, 2)),")
    println(io, "    values: &[")
    for j in 1:size(matrix, 1)
        println(io, "        ", join(repr.(Float64.(matrix[j, :])), ", "), ",")
    end
    println(io, "    ],")
    println(io, "};")
end

length(ARGS) == 1 || error("Usage: julia --project=<ConvolutionInterpolations.jl> tools/export_kernels.jl <output.rs>")

open(ARGS[1], "w") do io
    println(io, "// Generated by tools/export_kernels.jl from ConvolutionInterpolations.jl: do not edit by hand.")
    println(io)

    # ---- kernel column tables, for every derivative order ------------------------------------
    println(io, "// Column polynomials of the kernels and their derivatives. For a point at position t in")
    println(io, "// [0, 1] within its cell, with tau = 1 - t, the weight of coefficient i - eqs + k")
    println(io, "// (k = 1 ... 2*eqs) is column k evaluated at tau; derivative weights are then scaled by")
    println(io, "// (-1/h)^order. `rows` holds the coefficients row by row, from the highest power of tau")
    println(io, "// down, so that Horner's scheme runs over the rows: w <- w*tau + row.")
    println(io)
    println(io, "pub struct ColumnTable {")
    println(io, "    /// Number of columns (2*eqs)")
    println(io, "    pub columns: usize,")
    println(io, "    /// (degree + 1) rows of `columns` coefficients each, highest power of tau first")
    println(io, "    pub rows: &'static [f64],")
    println(io, "}")
    for kernel in KERNELS, order in 0:MAX_DERIVATIVE[kernel]
        rows, ncols = table_rows(kernel, order)
        println(io)
        println(io, "pub const $(const_name(kernel, order)): ColumnTable = ColumnTable {")
        println(io, "    columns: $ncols,")
        println(io, "    rows: &[")
        for row in rows
            println(io, "        ", join(repr.(row), ", "), ",")
        end
        println(io, "    ],")
        println(io, "};")
    end
    println(io)
    println(io, "/// The column table of a kernel and derivative order, if it was exported")
    println(io, "pub fn column_table(kernel: &str, order: i32) -> Option<&'static ColumnTable> {")
    println(io, "    match (kernel, order) {")
    for kernel in KERNELS, order in 0:MAX_DERIVATIVE[kernel]
        println(io, "        (\"$kernel\", $order) => Some(&$(const_name(kernel, order))),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")
    println(io)
    println(io, "/// The highest derivative order of a kernel (0 for :a0 and :a1), if the kernel exists")
    println(io, "pub fn max_derivative(kernel: &str) -> Option<i32> {")
    println(io, "    match kernel {")
    println(io, "        \"a0\" => Some(0),")
    for kernel in KERNELS
        println(io, "        \"$kernel\" => Some($(MAX_DERIVATIVE[kernel])),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")

    # ---- ghost-point matrices ----------------------------------------------------------------
    println(io)
    println(io, "// Ghost-point matrices of the boundary conditions. Row j gives the weights of the first")
    println(io, "// `cols` data values next to a boundary (mean-centered, nearest first) for the j-th ghost")
    println(io, "// point beyond that boundary. Only the first eqs - 1 rows are used.")
    println(io)
    println(io, "pub struct GhostMatrix {")
    println(io, "    /// Number of ghost points the matrix provides")
    println(io, "    pub rows: usize,")
    println(io, "    /// Number of data values each ghost point is computed from")
    println(io, "    pub cols: usize,")
    println(io, "    /// The weights, row by row")
    println(io, "    pub values: &'static [f64],")
    println(io, "}")
    write_ghost_matrix(io, "LINEAR_GHOST", CI.LINEAR_GHOST_MATRIX)
    write_ghost_matrix(io, "QUADRATIC_GHOST", CI.QUADRATIC_GHOST_MATRIX)
    for kernel in GHOST_KERNELS
        write_ghost_matrix(io, uppercase(string(kernel)) * "_POLY_GHOST", CI.POLYNOMIAL_GHOST_COEFFS[kernel])
    end
    println(io)
    println(io, "/// The polynomial ghost matrix of a kernel, if it has ghost points")
    println(io, "pub fn poly_ghost_matrix(kernel: &str) -> Option<&'static GhostMatrix> {")
    println(io, "    match kernel {")
    for kernel in GHOST_KERNELS
        println(io, "        \"$kernel\" => Some(&$(uppercase(string(kernel)))_POLY_GHOST),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")
end