# tools/export_kernels.jl
#
# Writes the exact column polynomials of every kernel as Rust source, for convinterp. Every
# coefficient is derived exactly by ConvolutionInterpolations.jl and rounded once to Float64, so
# both implementations use identical kernel weights.
#
# Usage, from the convinterp folder:
#     julia --project=C:\Users\Nikolaj\Git\ConvolutionInterpolations.jl tools/export_kernels.jl src/kernels.rs
# Writes only the file given as the argument.

using ConvolutionInterpolations
const CI = ConvolutionInterpolations

# Kernels with polynomial columns (:a0 is piecewise constant, handled separately in Rust)
const KERNELS = (:a1, :a3, :a4, :a5, :a7, :b5, :b7, :b9, :b11, :b13)
# Orders to export: interpolation only for now (derivatives and integrals follow later)
const ORDERS = (0,)

# Rust constant name, e.g. B5_D0 for kernel :b5, order 0
const_name(kernel, order) = uppercase(string(kernel)) * "_D$order"

# The columns of a kernel and order as rows of Float64 coefficients, from the highest power of
# τ down (the order Horner's scheme uses), one entry per column; and the number of columns
function table_rows(kernel, order)
    columns = CI._column_polynomials_exact(kernel, order)   # column c: coefficients of τ^0, τ^1, …
    degree = maximum(length, columns) - 1
    rows = [[k <= length(col) ? Float64(col[k]) : 0.0 for col in columns] for k in degree+1:-1:1]
    return rows, length(columns)
end

length(ARGS) == 1 || error("Usage: julia --project=<ConvolutionInterpolations.jl> tools/export_kernels.jl <output.rs>")

open(ARGS[1], "w") do io
    println(io, "// Generated by tools/export_kernels.jl from ConvolutionInterpolations.jl: do not edit by hand.")
    println(io, "//")
    println(io, "// Column polynomials of the kernels. For a point at position t in [0, 1] within its cell,")
    println(io, "// with tau = 1 - t, the weight of coefficient i - eqs + k (k = 1 ... 2*eqs) is column k")
    println(io, "// evaluated at tau. `rows` holds the coefficients row by row, from the highest power of tau")
    println(io, "// down, so that Horner's scheme runs over the rows: w <- w*tau + row.")
    println(io)
    println(io, "pub struct ColumnTable {")
    println(io, "    /// Number of columns (2*eqs)")
    println(io, "    pub columns: usize,")
    println(io, "    /// (degree + 1) rows of `columns` coefficients each, highest power of tau first")
    println(io, "    pub rows: &'static [f64],")
    println(io, "}")
    for kernel in KERNELS, order in ORDERS
        rows, ncols = table_rows(kernel, order)
        println(io)
        println(io, "pub const $(const_name(kernel, order)): ColumnTable = ColumnTable {")
        println(io, "    columns: $ncols,")
        println(io, "    rows: &[")
        for row in rows
            println(io, "        ", join(repr.(row), ", "), ",")
        end
        println(io, "    ],")
        println(io, "};")
    end
    println(io)
    println(io, "/// The column table of a kernel and order, if it was exported")
    println(io, "pub fn column_table(kernel: &str, order: i32) -> Option<&'static ColumnTable> {")
    println(io, "    match (kernel, order) {")
    for kernel in KERNELS, order in ORDERS
        println(io, "        (\"$kernel\", $order) => Some(&$(const_name(kernel, order))),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")
end