# tools/export_kernels.jl
#
# Writes the exact column polynomials of every kernel (values, derivatives and integrals), and the
# ghost-point matrices of the boundary conditions, as Rust source for convinterp. Every
# coefficient comes from ConvolutionInterpolations.jl, so both implementations use identical values.
#
# Usage, from the convinterp folder:
#     julia --project=C:\Users\Nikolaj\Git\ConvolutionInterpolations.jl tools/export_kernels.jl src/kernels.rs
# Writes only the file given as the argument.

using ConvolutionInterpolations
const CI = ConvolutionInterpolations

# Kernels with polynomial columns (:a0 is piecewise constant, handled separately in Rust), with the
# highest derivative order the Julia package defines for each
const MAX_DERIVATIVE = Dict(:a1 => 0, :a3 => 1, :a4 => 1, :a5 => 1, :a7 => 1,
                            :b5 => 3, :b7 => 5, :b9 => 6, :b11 => 7, :b13 => 7)
const KERNELS = (:a1, :a3, :a4, :a5, :a7, :b5, :b7, :b9, :b11, :b13)
# Kernels with ghost points (:a0 and :a1 have none) and their polynomial ghost matrices
const GHOST_KERNELS = (:a3, :a4, :a5, :a7, :b5, :b7, :b9, :b11, :b13)

# Every exported order of a kernel: integral orders −m down to the Julia package's highest
# (its own _max_integral_order), then the interpolant (0) and the derivatives
orders(kernel) = -CI._max_integral_order[kernel]:MAX_DERIVATIVE[kernel]

# Rust constant name, e.g. B5_D2 for kernel :b5, derivative order 2, and B5_I2 for order −2
const_name(kernel, order) = uppercase(string(kernel)) * (order >= 0 ? "_D$order" : "_I$(-order)")

# The columns of a kernel and order as rows of Float64 coefficients, from the highest power of
# τ down (the order Horner's scheme uses), one entry per column; and the number of columns.
# For an integral order −m the columns hold the m-fold antiderivative Kₘ, which has parity (−1)^m:
# multiplying by (−1)^m (exactly, before rounding) makes column k at τ = 1 − t equal Kₘ of the
# eager stencil coefficient k, the same column order as the derivative tables.
function table_rows(kernel, order)
    columns = CI._column_polynomials_exact(kernel, order)   # column c: coefficients of τ^0, τ^1, …
    flip = (order < 0 && isodd(order)) ? -1 : 1             # (−1)^m for integral order −m, else 1
    degree = maximum(length, columns) - 1
    rows = [[k <= length(col) ? Float64(flip * col[k]) : 0.0 for col in columns] for k in degree+1:-1:1]
    return rows, length(columns)
end

# Write a ghost matrix as a Rust GhostMatrix constant, row by row (row j: ghost point j)
function write_ghost_matrix(io, name, matrix)
    println(io)
    println(io, "pub const $name: GhostMatrix = GhostMatrix {")
    println(io, "    rows: $(size(matrix, 1)),")
    println(io, "    cols: $(size(matrix, 2)),")
    println(io, "    values: &[")
    for j in 1:size(matrix, 1)
        println(io, "        ", join(repr.(Float64.(matrix[j, :])), ", "), ",")
    end
    println(io, "    ],")
    println(io, "};")
end

length(ARGS) == 1 || error("Usage: julia --project=<ConvolutionInterpolations.jl> tools/export_kernels.jl <output.rs>")

open(ARGS[1], "w") do io
    println(io, "// Generated by tools/export_kernels.jl from ConvolutionInterpolations.jl: do not edit by hand.")
    println(io)

    # ---- kernel column tables, for every derivative and integral order -----------------------
    println(io, "// Column polynomials of the kernels, their derivatives and their integrals. For a point at")
    println(io, "// position t in [0, 1] within its cell, with tau = 1 - t, the weight of coefficient")
    println(io, "// i - eqs + k (k = 1 ... 2*eqs) is column k evaluated at tau; derivative weights are then")
    println(io, "// scaled by (-1/h)^order. For integral order -m (tables named _Im) column k at tau is the")
    println(io, "// m-fold antiderivative K_m of coefficient i - eqs + k itself (the sign (-1)^m is folded in),")
    println(io, "// before anchoring and the scale h^m. `rows` holds the coefficients row by row, from the")
    println(io, "// highest power of tau down, so that Horner's scheme runs over the rows: w <- w*tau + row.")
    println(io)
    println(io, "pub struct ColumnTable {")
    println(io, "    /// Number of columns (2*eqs)")
    println(io, "    pub columns: usize,")
    println(io, "    /// (degree + 1) rows of `columns` coefficients each, highest power of tau first")
    println(io, "    pub rows: &'static [f64],")
    println(io, "}")
    for kernel in KERNELS, order in orders(kernel)
        rows, ncols = table_rows(kernel, order)
        println(io)
        println(io, "pub const $(const_name(kernel, order)): ColumnTable = ColumnTable {")
        println(io, "    columns: $ncols,")
        println(io, "    rows: &[")
        for row in rows
            println(io, "        ", join(repr.(row), ", "), ",")
        end
        println(io, "    ],")
        println(io, "};")
    end
    println(io)
    println(io, "/// The column table of a kernel and order (negative for integrals), if it was exported")
    println(io, "pub fn column_table(kernel: &str, order: i32) -> Option<&'static ColumnTable> {")
    println(io, "    match (kernel, order) {")
    for kernel in KERNELS, order in orders(kernel)
        println(io, "        (\"$kernel\", $order) => Some(&$(const_name(kernel, order))),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")
    println(io)
    println(io, "/// The highest derivative order of a kernel (0 for :a0 and :a1), if the kernel exists")
    println(io, "pub fn max_derivative(kernel: &str) -> Option<i32> {")
    println(io, "    match kernel {")
    println(io, "        \"a0\" => Some(0),")
    for kernel in KERNELS
        println(io, "        \"$kernel\" => Some($(MAX_DERIVATIVE[kernel])),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")
    println(io)
    println(io, "/// The highest integral order m (derivative order -m) of a kernel, if the kernel exists")
    println(io, "pub fn max_integral(kernel: &str) -> Option<i32> {")
    println(io, "    match kernel {")
    println(io, "        \"a0\" => Some($(CI._max_integral_order[:a0])),")
    for kernel in KERNELS
        println(io, "        \"$kernel\" => Some($(CI._max_integral_order[kernel])),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")

    # ---- integral anchoring tables -----------------------------------------------------------
    println(io)
    println(io, "// Anchoring data of integral order m, for the 2*eqs - 1 coefficients j within reach of the")
    println(io, "// anchor (row j - 1 for coefficient j, 1-based as in ConvolutionInterpolations.jl).")
    println(io, "// `taylor` row j: K_{m-r}(eqs - j) for r = 0 ... m-1 (Julia's _anchor_taylor_table), the")
    println(io, "// Taylor correction of the anchored stencil weights. `entries` row j: the coefficients of")
    println(io, "// t^0 ... t^(m-1) of the entry polynomial of coefficient j into the left tail (Julia's")
    println(io, "// _near_anchor_entries). Both exact in Julia, rounded once to Float64.")
    println(io)
    println(io, "pub struct AnchorTable {")
    println(io, "    /// Number of rows (2*eqs - 1)")
    println(io, "    pub rows: usize,")
    println(io, "    /// The integral order m: the number of values in each row")
    println(io, "    pub order: usize,")
    println(io, "    /// Taylor values K_{m-r}(eqs - j), row by row")
    println(io, "    pub taylor: &'static [f64],")
    println(io, "    /// Entry polynomial coefficients, row by row, lowest power of t first")
    println(io, "    pub entries: &'static [f64],")
    println(io, "}")
    anchor_kernels = (:a0, KERNELS...)                     # :a0 too: Julia gives its values in closed form
    anchor_name(kernel, m) = uppercase(string(kernel)) * "_ANCHOR_I$m"
    for kernel in anchor_kernels, m in 1:CI._max_integral_order[kernel]
        eqs = CI.get_equations_for_degree(kernel)
        taylor = CI._anchor_taylor_table(Float64, kernel, m, eqs)    # (2eqs − 1) × m
        entries = CI._near_anchor_entries(Float64, kernel, m, eqs)   # (2eqs − 1) × m
        println(io)
        println(io, "pub const $(anchor_name(kernel, m)): AnchorTable = AnchorTable {")
        println(io, "    rows: $(size(taylor, 1)),")
        println(io, "    order: $m,")
        println(io, "    taylor: &[")
        for j in 1:size(taylor, 1)
            println(io, "        ", join(repr.(taylor[j, :]), ", "), ",")
        end
        println(io, "    ],")
        println(io, "    entries: &[")
        for j in 1:size(entries, 1)
            println(io, "        ", join(repr.(entries[j, :]), ", "), ",")
        end
        println(io, "    ],")
        println(io, "};")
    end
    println(io)
    println(io, "/// The anchoring data of a kernel and integral order m (derivative order -m), if exported")
    println(io, "pub fn anchor_table(kernel: &str, m: i32) -> Option<&'static AnchorTable> {")
    println(io, "    match (kernel, m) {")
    for kernel in anchor_kernels, m in 1:CI._max_integral_order[kernel]
        println(io, "        (\"$kernel\", $m) => Some(&$(anchor_name(kernel, m))),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")

    # ---- ghost-point matrices ----------------------------------------------------------------
    println(io)
    println(io, "// Ghost-point matrices of the boundary conditions. Row j gives the weights of the first")
    println(io, "// `cols` data values next to a boundary (mean-centered, nearest first) for the j-th ghost")
    println(io, "// point beyond that boundary. Only the first eqs - 1 rows are used.")
    println(io)
    println(io, "pub struct GhostMatrix {")
    println(io, "    /// Number of ghost points the matrix provides")
    println(io, "    pub rows: usize,")
    println(io, "    /// Number of data values each ghost point is computed from")
    println(io, "    pub cols: usize,")
    println(io, "    /// The weights, row by row")
    println(io, "    pub values: &'static [f64],")
    println(io, "}")
    write_ghost_matrix(io, "LINEAR_GHOST", CI.LINEAR_GHOST_MATRIX)
    write_ghost_matrix(io, "QUADRATIC_GHOST", CI.QUADRATIC_GHOST_MATRIX)
    for kernel in GHOST_KERNELS
        write_ghost_matrix(io, uppercase(string(kernel)) * "_POLY_GHOST", CI.POLYNOMIAL_GHOST_COEFFS[kernel])
    end
    println(io)
    println(io, "/// The polynomial ghost matrix of a kernel, if it has ghost points")
    println(io, "pub fn poly_ghost_matrix(kernel: &str) -> Option<&'static GhostMatrix> {")
    println(io, "    match kernel {")
    for kernel in GHOST_KERNELS
        println(io, "        \"$kernel\" => Some(&$(uppercase(string(kernel)))_POLY_GHOST),")
    end
    println(io, "        _ => None,")
    println(io, "    }")
    println(io, "}")
end